language: java
sudo: false

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

deploy:
  - provider: script
    script: ./gradlew annotations:gitPublishPush
    skip_cleanup: true
    on:
      tags: true

  - provider: script
    script: ./gradlew annotations:gitPublishPush
    skip_cleanup: true
    on:
      branch: master

notifications:
  email: false
  slack: ouroath:M5cVriVZt6P4yiHdkH84N10l
